toggle_section: true

section_title: Core[%br%] Values
section_desc: Our core values are the foundation of everything we do, guiding our decisions, shaping our culture, and driving us toward a meaningful future.
img_desc: "Sunder's core values: stewardship, unity, nobility, disruption, empathy, and respect."

cta:
  text: Join the squad
  text_desc:
  url: /join
  new_tab: false
