backend:
  # Use netlify identity as backend
  name: "git-gateway"
  branch: "main"
  repo: "https://github.com/AXYS-Creative/starter-template-cms.git" # CHANGE ME
media_folder: "src/static/img"
public_folder: "/static/img"
site_url: https://starter-template-cms.netlify.app # CHANGE ME # On admin login page, this adds a 'go back to site' link. Also added in the corner when logged in.
display_url: https://starter-template-cms.netlify.app # CHANGE ME # In admin dashboard, this addes the URL in the corner 'View Live'. Used with 'preview_path' for collection viewing.
logo_url: https://starter-template-cms.netlify.app/static/img/icons/admin-logo.svg # CHANGE ME # On admin login page, this adds a custom logo.

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
publish_mode: editorial_workflow
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/posts"
    preview_path: "posts/blog/{{filename}}/"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["Tags", "created", "from", "config.yml"]
      - label: "Cover Image" # Only seems to work with .md collections
        name: "image"
        widget: "image"
        required: false
  - name: "page_library"
    label: "Page - Library"
    description: >
      Library for all UI components
    files:
      - name: "marquee"
        label: "Marquee"
        file: "src/_data/library/marquee.yaml"
        preview_path: "#"
        editor:
          preview: false
        fields:
          - name: "marquee_toggle"
            label: "Marquee Toggle"
            widget: "boolean"
            hint: "Hide or show the discount marquee."
          - name: "marquee_text"
            label: "Marquee Text"
            required: true
          - name: "marquee_scrub"
            label: "Marquee Scrub"
            widget: "boolean"
            hint: "Change velocity based on scroll speed."
      - name: "accordion"
        label: "Accordion"
        file: "src/_data/library.accordion.yaml"
        preview_path: "#"
        editor:
          preview: false
        fields:
          - name: "accordion_behavior_single"
            label: "Single Open"
            widget: "boolean"
            required: false
            hint: "Allow only one item to be open at a time."
          - name: "accordion_data"
            label: "accordion Items"
            label_singular: "Item"
            widget: "list"
            fields:
              - name: "title"
                label: "Title"
                widget: "string"
                required: true
              - name: "content"
                label: "Content"
                widget: "text"
                required: true
      - name: "carousel_snap"
        label: "Snap Carousel"
        file: "src/_data/library/carousel_snap.yaml"
        preview_path: "/library#carousel-snap"
        editor:
          preview: false
        fields:
          - name: "autoplay"
            label: "Autoplay"
            widget: "object"
            summary: "{{fields.enabled}}, {{fields.interval}}"
            fields:
              - name: "interval"
                label: "Interval"
                widget: "number"
                hint: "i.e. 5000 — Interval in milliseconds. Remove the value to disable autoplay"
              - name: "allow_user_toggle"
                label: "Allow User Toggle"
                widget: "boolean"
                hint: "Allow users to toggle autoplay (UX enhancement)."
          - name: "list"
            label: "Carousel Items"
            label_singular: "Item"
            widget: "list"
            fields:
              - name: "title"
                label: "Title"
                widget: "string"
                required: true
              - name: "description"
                label: "Description"
                widget: "text"
                required: true
              - name: "image"
                label: "Image"
                widget: "image"
  - name: "meta_data"
    label: "Meta Data"
    description: >
      Edit the site's meta data here. Open Graph dimensions: 1200x630. Open graph file name: open-graph.png
    files:
      - name: "meta_data"
        label: "Meta Data"
        file: "src/_data/meta_data.yaml"
        editor:
          preview: false
        fields:
          - name: "site_name"
            label: "Site Name"
            widget: "string"
            required: true
            hint: "Sample Business Co"
          - name: "url"
            label: "URL"
            widget: "string"
            required: true
            hint: "Full URL to your site"
          - name: "author"
            label: "Author"
            widget: "string"
            required: true
            hint: "Person or company name"
          - name: "contact_email"
            label: "Contact Email"
            widget: "string"
            required: true
            hint: "Email address for rich results schema"
          - name: "theme_color"
            label: "Theme Color"
            widget: "color"
            required: true
            hint: "Hex color code for overflow color on some devices"
          - name: "og_title"
            label: "Open Graph Title"
            widget: "string"
            required: true
            hint: "Sample Business | Motto here"
          - name: "og_description"
            label: "Open Graph Description"
            widget: "string"
            required: true
            hint: "Keep at least 100 characters"
          - name: "og_image"
            label: "Open Graph Image"
            widget: "image"
            default: "https://CHANGE-ME.com/static/img/og-image.png"
            required: true
            hint: "Recommended formats: PNG or JPG. Recommended image dimensions: 1200 x 630 pixels. File size should be under 8 MB."
